name: dating_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # region Packages
  intl: ^0.18.0
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.12
  go_router: ^13.0.0

  # Service Locator
  get_it: ^7.2.0

  # Network
  dio: ^5.0.0

  # Logging
  logger: ^2.0.2+1

  # Freezed
  freezed_annotation: ^2.2.0

  # Equatable
  equatable: ^2.0.5

  # endregion packages

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  google_fonts:
  intl_phone_field: ^3.1.0
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.5

  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0

  # add
  step_progress_indicator: ^1.0.0
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  cloud_firestore: ^4.13.6
  uuid: ^4.2.2
  rxdart: ^0.27.2
  google_maps_flutter: ^2.2.5
  geolocator: ^10.1.0
  formz: ^0.4.1
  form_inputs:
    path: packages/form_inputs


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
