// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx683ozMtBPYfbaM-GJYD3YX3rNysCq3M',
    appId: '1:816521819994:android:32a44d626d80f70d66e563',
    messagingSenderId: '816521819994',
    projectId: 'dating-daf3a',
    storageBucket: 'dating-daf3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfNts4_I_MKWiKTYij3RCWSC0MXbyMH4',
    appId: '1:816521819994:ios:df4686208cc2964f66e563',
    messagingSenderId: '816521819994',
    projectId: 'dating-daf3a',
    storageBucket: 'dating-daf3a.appspot.com',
    androidClientId: '816521819994-7es6cajq9bbqmg9in66a19rh2p69fevt.apps.googleusercontent.com',
    iosClientId: '816521819994-vnkdgjr0u9rbvhjqekgm2brn8ksbc06c.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
